name: continuous-integration/gh-actions/cli

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macOS-latest
    env:
      CCACHE_COMPRESS: 1
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/cache@v2
      with:
        path: /Users/runner/Library/Caches/ccache
        key: ccache-macos-build-${{ github.sha }}
        restore-keys: ccache-macos-build-
    - name: install dependencies
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew bundle --file=contrib/apple/brew
    - name: build
      run: |
        ccache --max-size=150M
        make -j3
    - name: Upload mac artifacts
      uses: actions/upload-artifact@master
      with:
        name: macos
        path: 'build/**/**/arqma*'

  build-osx-depends:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install ArQmA dependencies
      run:  sudo apt -y install cmake ccache imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools curl bsdmainutils python3-setuptools
    - name: add SDK
      run: git clone -b arqma https://github.com/malbit/MacOSX-SDKs.git contrib/depends/SDKs
    - name: build
      run: |
        ccache --max-size=150M
        make depends target=x86_64-apple-darwin19.2.0 -j2
    - name: Upload mac artifacts
      uses: actions/upload-artifact@master
      with:
        name: MacOSX
        path: 'build/**/**/arqma*'

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install ArQmA dependencies
      run: sudo apt -y install build-essential cmake libboost-all-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libsodium-dev libhidapi-dev libusb-1.0-0-dev gperf libreadline-dev
    - name: build
      run: make release -j2
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: linux
        path: 'build/**/**/arqma*'

  build-depends-compat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install ArQmA dependencies
      run: sudo apt -y install build-essential cmake libboost-all-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libsodium-dev libhidapi-dev libusb-1.0-0-dev gperf libreadline-dev
    - name: build
      run: make depends-compat target=x86_64-linux-gnu -j2
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: linux-compat
        path: 'build/x86_64-linux-gnu-compat/release/bin/arqma*'
